version: "3"
networks:
  myprojectnetwork:
    external: true
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=myproject
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://root:root@mongo:27017/myproject?authSource=admin
      - APP_PORT=3100

    container_name: backendapp
    restart: always
    ports:
      - 3100:3100
    links:
      - mongo
  frontend:
    stdin_open: true
    build: ./frontend
    environment:
      - NODE_ENV=development
    container_name: frontendapp
    restart: always
    ports:
      - "3000:3000"
    networks:
      - myprojectnetwork
