version: "3"
networks:
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=myproject
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
  backend:
    build: ./backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - APP_PORT=${APP_PORT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXP_TIME=${JWT_EXP_TIME}
    container_name: backendapp
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    links:
      - mongo
  frontend:
    stdin_open: true
    build: ./frontend
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_URL=http://localhost:${APP_PORT}/v1
      - REACT_APP_PORT=${REACT_APP_PORT}
    container_name: frontendapp
    restart: always
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}