version: "3"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=myproject
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
  backend:
    image: node:12.18.3-alpine
    working_dir: /usr/src/backend/app
    command: yarn start
    volumes:
      - ./:/usr/src/backend/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - APP_PORT=${APP_PORT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXP_TIME=${JWT_EXP_TIME}
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    links:
      - mongo